# Generated by Django 6.1 on 2026-08-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('senior_citizen', models.IntegerField(default=0)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('married', models.CharField(blank=True, max_length=5)),
                ('dependents', models.CharField(blank=True, max_length=5)),
                ('partner', models.CharField(blank=True, max_length=5)),
                ('tenure_months', models.IntegerField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=30)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('paperless_billing', models.CharField(blank=True, max_length=5)),
                ('monthly_charges', models.FloatField(blank=True, null=True)),
                ('total_charges', models.FloatField(blank=True, null=True)),
                ('phone_service', models.CharField(blank=True, max_length=5)),
                ('internet_service', models.CharField(blank=True, max_length=20)),
                ('service_count', models.IntegerField(blank=True, null=True)),
                ('unlimited_data', models.CharField(blank=True, max_length=5)),
                ('streaming_tv', models.CharField(blank=True, max_length=5)),
                ('streaming_movies', models.CharField(blank=True, max_length=5)),
                ('streaming_music', models.CharField(blank=True, max_length=5)),
                ('satisfaction_level', models.CharField(blank=True, max_length=10)),
                ('open_issue_count', models.IntegerField(default=0)),
                ('close_issue_count', models.IntegerField(default=0)),
                ('support_interaction_count', models.IntegerField(default=0)),
                ('resolution_status_open_closed', models.CharField(blank=True, max_length=15)),
                ('customer_status', models.CharField(blank=True, max_length=15)),
                ('churn', models.CharField(blank=True, max_length=5)),
                ('churn_score_target', models.FloatField(blank=True, null=True)),
                ('cltv', models.FloatField(blank=True, null=True)),
                ('predicted_churn_score', models.FloatField(blank=True, null=True)),
                ('risk_band', models.CharField(blank=True, max_length=12)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-predicted_churn_score'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=10)),
                ('rows_added', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('rows_skipped_duplicate', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signals', models.JSONField(blank=True, default=list)),
                ('rationale', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('llm_sentiment', models.CharField(blank=True, max_length=10)),
                ('suggested_action', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='customer_signal.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_customer_id', models.CharField(blank=True, db_index=True, max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField()),
                ('turns_json', models.JSONField(blank=True, default=list)),
                ('feedback_text', models.TextField(blank=True)),
                ('stated_sentiment', models.CharField(blank=True, max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='customer_signal.customer')),
            ],
        ),
    ]
