# Generated by Django 6.1 on 2026-08-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_signal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='storage_folder',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
