"""
Django settings for Setting project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path


# =============================================================================
# BASE DIRECTORY
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# =============================================================================
# SECURITY
# =============================================================================

SECRET_KEY = "django-insecure-ievkb41_3bos)xl@8eeyqmhjmt$fenghje!&+p7+k+qri^7i!&"

DEBUG = True #False#True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]


# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    # Django built-in applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Your application
    "customer_signal",
]


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise serves static files
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =============================================================================
# URL / WSGI
# =============================================================================

ROOT_URLCONF = "Setting.urls"

WSGI_APPLICATION = "Setting.wsgi.application"


# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        "DIRS": [
            BASE_DIR / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =============================================================================
# DATABASE
# =============================================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "/static/"

# Source static files
#
# Example:
#
# static/
# ├── css/
# │   └── dashboard.css
# └── js/
#     └── dashboard.js
#
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Destination for:
#
#     python manage.py collectstatic
#
STATIC_ROOT = BASE_DIR / "staticfiles"


# =============================================================================
# STATIC FILE STORAGE / WHITENOISE
# =============================================================================
#
# IMPORTANT:
#
# Do NOT use CompressedManifestStaticFilesStorage during development if
# staticfiles.json has not been generated correctly.
#
# This avoids:
#
# ValueError: Couldn't load manifest 'staticfiles.json'
#
# WhiteNoise will still serve the files.
#

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },

    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# =============================================================================
# WHITENOISE
# =============================================================================

# Enable WhiteNoise compression.
WHITENOISE_USE_FINDERS = True

# Optional: allow WhiteNoise to serve static files in development.
WHITENOISE_AUTOREFRESH = True


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# EMAIL
# =============================================================================
#
# Your previous setting used:
#
#     MAILERS = {...}
#
# Django expects EMAIL_BACKEND.
#
# Console backend prints emails in the terminal instead of sending
# real emails. This is ideal during development.
#

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


# =============================================================================
# OPTIONAL EMAIL SETTINGS FOR PRODUCTION
# =============================================================================
#
# When you are ready to use a real SMTP provider, replace the console
# backend above with something like:
#
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.example.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = "your-email@example.com"
# EMAIL_HOST_PASSWORD = "your-password"
# DEFAULT_FROM_EMAIL = "your-email@example.com"
#
# Do NOT hard-code real passwords in this file for production.
# Use environment variables instead.
# =============================================================================
